### ISSUE TITLE
Conway spec prose

### ISSUE THREAD

**Issue by WhatisRT** [input-output-hk/formal-ledger-specifications#145]
The spec needs some explanations. It should be structured in a similar fashion to the older specifications. These are the sections that need to be written to explain all the new features:

- [x] Protocol parameters (only new ones need to be explained)
- [x] Governance actions
- [x] Voting (should explain the CC, DReps and give a broad overview of the lifetime of a governance action)
- [x] Enactment
- [ ] Ratification

They don't have to be perfect for now, we can improve them as we keep polishing things.

**Comment by jmchapman** [comment]
Please make separate PRs for each one

**Comment by williamdemeo** [comment]
oops, not sure why/how I closed this issue.  Perhaps once I changed the last PR connected to this issue from "draft" to "ready for review" the issue was closed automatically?  Anyway, that was unintended... sorry about that!

**Comment by WhatisRT** [comment]
No, this issue is linked to your PRs & gets closed once one is merged. I tried to get it to not close it automatically, but I couldn't figure out how.

The CI failure isn't your fault, the runner runs out of disk space for some reason (and this isn't the first time this happened). I've made an issue for it (#167), you don't need to look into that.
