### ISSUE TITLE
Flesh out state machine explanation

### ISSUE THREAD

**Issue by WhatisRT** [input-output-hk/formal-ledger-specifications#186]
There's a short description about the state machine formalism in the introduction that I wrote for the workshop in Parma. We should have a full section about it, and in particular:

- explain the small-step to big-step transformer (probably with a figure)
- say a bit more about `Computational`, that we can derive it, and some of the properties it has

**Comment by jmchapman** [comment]
what's the status of this? Is it going to move to the next milestone?
