### ISSUE TITLE
PDF cleanup (cont'd from issue #146)

### ISSUE THREAD

**Issue by polinavino** [input-output-hk/formal-ledger-specifications#258]
- [ ] explain Agda notations/concepts/syntax
   - [x] `record` definitions
   - [x] `open` for records
   - [ ] `Type` versus `Set`
   - [ ] implicit arguments
   - [x] `Σ`
   - [ ] `module`
   - [ ] `data`
   - [ ] `λ where` syntax
   - [ ] type definitions that end in `-> Set` or `-> Type`; they are actually constructing a proposition where the proof is relevant. Should we be more consistent about using our `Type` alias throughout?  Should we sometimes use another alias, like `Prop`?  Would this make the document easier to read or would it create even more confusion?
- [ ] define/explain different notions of equality, including but not limited to,
   - [ ] `_≡_`
   - [ ] `_≗_`
- [ ] Replace `≡ᵉ` with `≡` (we may not be able to actually make this replacement in the Agda code, so we may have to do some preprocessing of the LaTeX)
- [ ] explain the following syntax/notation
   - [ ] `⟨_⟩`
   - [ ] `Σᵐᵛ` (fig 12)
   - [ ] `_⊎_` (fig 12)
   - [ ] `_∷ʳ_` (fig 14)
   - [ ] `_⊢_⇀⦇_,GOV⦈_ = SS⇒BSi _⊢_⇀⦇_,GOV'⦈_` (fig 15)
   - [ ] `_↾_` (unnumbered fig after fig 20)
   - [ ] `_↾'_`
   - [ ] `ifᵈ_then_else_` (unnumbered fig after fig 20)
   - [ ] `⌊_⌋`
   - [ ] `_∣_` (fig 23)
   - [ ] `_⊖_` (fig 25)
   - [ ] `_∘₂_` (fig 25)
   - [ ] `_⁻¹` (fig 35)
   - [ ] `ℚ.0ℚ` (fig 36)
   - [ ] `_ℚ.≥_` (fig 36)
- [ ] Remove/rename the following
   - [ ] `mapˢ` - since we now have a `Functor` class, we can make an instance and write `map` instead
   - [ ] Remove `_ᶠᵐ` notation from sums by introducing a typeclass
   - [ ] `∅ᵐ` -> `∅`
   - [ ] `❴_❵ᵐ` -> `❴_❵`
   - [ ] `foldr` (fig 5)
   - [ ] `≗` (fig 5)
   - [ ] `_⟪$⟫_` (fig 25)
   - [ ] `_<$>_` (fig 25)
   - [ ] `sp-∘` `to-sp`
- [ ] Remove superscripts from `⟦_,...,_⟧` (probably via a typeclass)
- [ ] Can we remove `+ᵉ` somehow? We could change `HasAdd` so that `+` can take to different types, and then for a ring define some instances where you can always add natural numbers/integers. But maybe we can do something easier?
- [ ] Figure 3 missing `PolicyID` as abstract type (or probably should explain the special font for abstract types at least)
- [ ] list `DocHash` as abstract
- [ ] define/explain `ppdWellFormed`
- [ ] Fig. 4 `isVKey` and `isScript` are not defined
- [ ] Figure 8 (Protocol parameter declarations)
  - [ ] Can we move `Acnt` elsewhere?
  - [ ] discuss `threshold` function
- [ ] Fig. 12 has a lot of rules that don't have any preconditions i guess? explain that not all rules have a horizontal line and preconditions (or just make one so it looks consistent)
- [ ] Fig 12: explain symbols/notation (see list above) and give more details about transition in discussion in 7.3.
- [ ] Fig. 13 - format
- [ ] Fig 14 - `modifyMatch`
- [ ] Fig 15 - rules would be easier to read if all the `let` statements are above the line
- [ ] why is `Γ ⊢` used instead of say, `_  ⊢` when environment is irrelevant?
- [ ] Fig 20 - different font for abstract types than Fig 4, and figure doesn't fit on the page
- [ ] Fig 20 - `Tag` type isn't specified anywhere
- [ ] Fig 20 `mapPartial` `isInj_1` both need to be defined
- [ ] define `filter^m`
- [ ] `mapKeys`
- [ ] Figure 25 (Functions used for witnessing)
  - [ ] Replace `(utxo ˢ) ⟪$⟫ txins` with a more sensible notation. Ideally we could just write `utxo(txins)` (standard notation for applying a function to a set), but we can't. Maybe we could have a somewhat sensible notation in Agda that we filter out in the PDF with a preprocessor?
  - [ ] `<$>` is also inappropriate here, but that line has unfinished semantics ATM
- [ ] Figure 27, `txidBytes` and `hash` don't seem to be defined
- [ ] Figure on page 29 is too big
- [ ] `totExUnits`
- [ ] it's sort of hard to notice half-arrows in type definitions, eg. `PParams → DCert → DepositPurpose ⇀ Coin` , would be easier to read with brackets  `PParams → DCert → (DepositPurpose ⇀ Coin)`  or maybe even use some more noticeably different symbol
- [ ] Figure 34 (Types and proofs for the ratification of governance actions)
  - [ ] define `uncurry`
  - [x] That whole `where` block is quite unwieldy, maybe we can move some parts (like `isHF`) out of it?
  - [ ] Lots of Agda/Haskell knowledge required here, we should switch as much as possible to more commonly understandable notation (and everything that we can't needs to be explained in the `Notation` section)
- [ ] Figure 40 (NEWEPOCH transition system)
  - [ ] We should at least split this into `EPOCH` and `NEWEPOCH` like the Shelley spec
  - [ ] The module shenanigans and record updates make this one especially hard to read
  - [ ] We should replace `sucᵉ` by `... + 1`
- [ ] `verifyPrev` and especially `delayed` need better explanations. why does `delayed` call `verifyPrev`?
- [ ] Explain that multiple cold keys can delegate to a single hot key, which gives it more voting power.

**Comment by williamdemeo** [comment]
@polinavino I hope you don't mind, I revised/reorganized your list a bit.

**Comment by polinavino** [comment]
that looks much better, thank you!

**Comment by jmchapman** [comment]
@WhatisRT This list unmanageably big. 

Please can you have a call with @williamdemeo to go through it and split it up into sections, marking each one as "resolve by explanation","resolve by hiding/refactoring","won't do" where "won't do" means on balance it doesn't need explaining.

**Comment by WhatisRT** [comment]
Closing this in favour of #281, #282, #283, #285, #286, #287, #288 and #289.
