### ISSUE TITLE
Repo Preparation for MBO

### ISSUE THREAD

**Issue by ThatGuyLLC** [input-output-hk/formal-ledger-specifications#26]
This repo has been marked as core tech and is part of initiative of repo preparation, part of this includes adding needed missing documentation.
This repo in particular needs:

* [x] Include an informative README
* [x] Include a High Level 2 Sentence Description for purpose of Repo
* [x] Explain how to make a contribution (Contributing MD)
* [x] Include the Standard Code of Conduct
* [x] Use the Apache 2.0 License or agreed alternative
* [x] Identify the Core Maintainers

**Comment by JaredCorduan** [comment]
@WhatisRT is the core maintainer. Should this just be specified in the contributing doc?

**Comment by coot** [comment]
Yes, this should be mentioned in the `CONTRIBUTING.md` doc (or some other file, e.g. `*.cabal`, then just say in the `CONTRIBUTING.md` where one can find the current maintainer).

**Comment by JaredCorduan** [comment]
@coot - is the "High Level 2 Sentence Description for purpose of Repo" suppose to go in the GitHub "About" section? If so, it seems we need a second sentence.

**Comment by coot** [comment]
The current is good enough or me, but if you have an idea then go for it.

**Comment by JaredCorduan** [comment]
It's good enough for me too. Let's leave it as is, unless @WhatisRT has any ideas for a second sentence in the "About".

**Comment by coot** [comment]
I merged your PR, now the issue can be closed.

**Comment by WhatisRT** [comment]
Thank you for taking care of it @JaredCorduan
