### ISSUE TITLE
nix-build doesn't work

### ISSUE THREAD

**Issue by kwxm** [input-output-hk/formal-ledger-specifications#29]
I can't get any of the build instructions to work.  For example, `nix-build -A ledger.docs` gives (after a long time)
```
         Checking Interface.MonadReader.Instance (/build/src/Interface/MonadReader/Instance.agda).
         Checking Interface.MonadTC.Instance (/build/src/Interface/MonadTC/Instance.agda).
       Checking Tactic.Defaults (/build/src/Tactic/Defaults.agda).
/build/src/Axiom/Set/Rel.agda:78,22-31
<stdout>: commitBuffer: invalid argument (invalid character)
```
This looks like a locale issue, but adjusting locale variables in my shell doesn't help: I think it's probably something that needs to be fixed in the nix setup.  I've tried this on three different computers and the same thing happens on each.  I use nix in a number of other IOG repositories every day with no problems, so this issue seems to be specific to this repository.

**Comment by WhatisRT** [comment]
All packages in the nix build except for `agda` depend on `agdaLedger`, which looks like where this error is coming from, so it's expected that nothing would work when encountering this error. 

After running `nix-build -A ledger` myself I got a bunch of debug output while type checking `Axiom.Set.Rel`, which is prepended with a strange unicode character that I used to group things together, which I feel might be the most likely culprit in this case. It's probably best to disable that debug output anyway (and I already have in #28). You could try that locally by replacing `{ selection = All }` with `{ selection = All ; filter = Filter.⊥ }` in `src/Tactic/Defaults.agda`.

**Comment by kwxm** [comment]
> You could try that locally by replacing `{ selection = All }` with `{ selection = All ; filter = Filter.⊥ }` in `src/Tactic/Defaults.agda`.

Aha, that worked. Thank you!

**Comment by WhatisRT** [comment]
Agda 2.6.3 which should be out soon-ish will also have a `--transliterate` flag, which should prevent Agda from trying to print characters not supported by the locale. It's probably a good idea to turn that on in the nix build by default then. So I'll leave this open as a reminder to do so when we update.

**Comment by kwxm** [comment]
OK.  Thanks again for looking at this so quickly.

**Comment by williamdemeo** [comment]
> 

This worked for me too!

...on os/architecture:

Linux 5.15.0-59-generic #65-Ubuntu SMP Fri Jan 6 16:35:39 UTC 2023 x86_64 GNU/Linux

**Comment by WhatisRT** [comment]
Everything here should be fixed properly now.
