### ISSUE TITLE
Type classes for common structures

### ISSUE THREAD

**Issue by WhatisRT** [input-output-hk/formal-ledger-specifications#34]
We have a bunch of structures with lots of name clashes that would likely benefit a lot from being turned into type classes. Here are some:

- [x] Addition
- [x] Subtraction
- [x] Multiplication
- [x] All the inequalities
- [x] Decidable inequalities

**Comment by williamdemeo** [comment]
I've checked multiplication off the list because I can't find any instances of a decorated multiplication symbol.
